"""
Django settings for news project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
import keyring
from pathlib import Path
from django.conf import settings


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xh8tn3widj15m+n_rf$=hbj9z=xaookchfw=_-@l2_0bvw0a-m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django.contrib.sites',
    'django.contrib.flatpages',
    'fpages',
    'newsapp',
    'accounts',
    'django_filters',

    'sign',
    'protect',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    'social_django',
    'allauth.socialaccount.providers.yandex',

    'django_apscheduler',

    'django_celery_beat',

]

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'social_core.backends.yandex.YandexOAuth2',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',

]

ROOT_URLCONF = 'news.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



WSGI_APPLICATION = 'news.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_DIRS = [BASE_DIR/'static']

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_EMAIL_VERIFICATION = 'none'

LOGIN_URL = '/sign/login/'
LOGIN_REDIRECT_URL = '/news/'
ACCOUNT_SIGNUP_REDIRECT_URL = "/sign/login/"
LOGOUT_REDIRECT_URL = "/sign/login/"
ACCOUNT_LOGOUT_REDIRECT_URL = "/sign/login/"

ACCOUNT_FORMS = {'signup': 'sign.models.BasicSignupForm'}

SOCIAL_AUTH_YANDEX_OAUTH2_KEY = 'your-client-id'
SOCIAL_AUTH_YANDEX_OAUTH2_SECRET = 'your-client-secret'



SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': 'ТВОЙ_CLIENT_ID_GOOGLE',
            'secret': 'ТВОЙ_CLIENT_SECRET_GOOGLE',
            'key': ''
        }
    },
    'yandex': {
        'APP': {
            'client_id': 'ТВОЙ_CLIENT_ID_YANDEX',
            'secret': 'ТВОЙ_CLIENT_SECRET_YANDEX',
            'key': ''
        }
    }
}



EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = keyring.get_password("django_email", "EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = keyring.get_password("django_email", "EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# формат даты, которую будет воспринимать наш задачник (вспоминаем модуль по фильтрам)
APSCHEDULER_DATETIME_FORMAT = "N j, Y, f:s a"

# если задача не выполняется за 25 секунд, то она автоматически снимается, можете поставить время побольше, но как правило, это сильно бьёт по производительности сервера
APSCHEDULER_RUN_NOW_TIMEOUT = 25  # Seconds

# Настройка celery и redis

CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# КЭШ

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.path.join(BASE_DIR, 'cache_files'),  # Папка для хранения кэша
        'TIMEOUT': None,  # Можно задать общий таймаут, но мы укажем его в декораторах
        'OPTIONS': {
            'MAX_ENTRIES': 1000,  # Ограничение на количество записей в кэше
        },
    }
}



import logging
from django.utils.log import CallbackFilter


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,  # Не убиваем стандартные логгеры Django
    'filters': {
        # Фильтр для отладки: сообщения только если DEBUG=True
        'debug_filter': {
            '()': 'django.utils.log.CallbackFilter',
            'callback': lambda record: settings.DEBUG,
        },
        # Фильтр для продакшена: сообщения только если DEBUG=False
        'production_filter': {
            '()': 'django.utils.log.CallbackFilter',
            'callback': lambda record: not settings.DEBUG,
        },
    },
    'formatters': {
        # Форматтер для general.log и security.log (обычный детальный вывод)
        'detailed': {
            'format': '{asctime} {levelname} {module} {message}',
            'style': '{',
        },
        # Форматтер для ошибок (errors.log) - путь и стек ошибки
        'error': {
            'format': '{asctime} {levelname} {message} {pathname} {exc_info}',
            'style': '{',
        },
    },
    'handlers': {
        # Консольный вывод через кастомный хендлер
        'console': {
            'level': 'DEBUG',
            'filters': ['debug_filter'],  # Только если DEBUG=True
            'class': 'news.logging_handlers.LevelBasedStreamHandler',  # Путь к кастомному хендлеру
        },
        # Файл для общих логов
        'general_file': {
            'level': 'INFO',
            'filters': ['production_filter'],  # Только если DEBUG=False
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'general.log'),
            'formatter': 'detailed',
        },
        # Файл только для ошибок
        'errors_file': {
            'level': 'ERROR',
            'filters': ['production_filter'],
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'errors.log'),
            'formatter': 'error',
        },
        # Файл только для безопасности
        'security_file': {
            'level': 'DEBUG',
            'filters': ['production_filter'],
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'security.log'),
            'formatter': 'detailed',
        },
        # Отправка ошибок на почту
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['production_filter'],
            'class': 'django.utils.log.AdminEmailHandler',
            'formatter': 'error',  # Без exc_info в письме (см. ТЗ)
        },
    },
    'loggers': {
        # Главный логгер Django
        'django': {
            'handlers': ['console', 'general_file', 'errors_file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        # Ошибки запросов
        'django.request': {
            'handlers': ['mail_admins', 'errors_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        # Ошибки самого сервера (runserver и т.д.)
        'django.server': {
            'handlers': ['mail_admins', 'errors_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        # Ошибки в шаблонах
        'django.template': {
            'handlers': ['errors_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        # Ошибки в работе базы данных
        'django.db.backends': {
            'handlers': ['errors_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        # Безопасность: только в отдельный security.log
        'django.security': {
            'handlers': ['security_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}