# Generated by Django 5.1.5 on 2025-03-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='date_sub',
            new_name='date_subscribed',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='categories',
            field=models.ManyToManyField(related_name='subscribers', to='newsapp.category'),
        ),
    ]
